language: cpp
sudo: false
cache:
  directories:
  - "$HOME/opt"
  - "$HOME/.ccache"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - ccache
    - g++-4.8
    - gcc-4.8
    - genromfs
    - libc6-i386
    - python-argparse
    - python-empy
    - python-serial
    - zlib1g-dev

before_install:
- pushd $HOME
- pushd $HOME/opt
- if [ ! -d "$HOME/opt/gcc-arm-none-eabi-4_9-2015q3" ]; then wget http://firmware.diydrones.com/Tools/PX4-tools/gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2
  && tar -xf gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2 ; fi
- popd
- mkdir -p $HOME/bin && ln -sf /usr/bin/gcc-4.8 $HOME/bin/gcc && ln -sf /usr/bin/g++-4.8
  $HOME/bin/g++ && exportline="export PATH=$HOME/bin:$HOME/opt/gcc-arm-none-eabi-4_9-2015q3/bin:$HOME/opt/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin:\$PATH"
  && if grep -Fxq "$exportline" ~/.profile; then echo nothing to do ; else echo $exportline
  >> ~/.profile; fi && . ~/.profile
- popd

before_script:
- mkdir -p $HOME/ccache-bin
- ln -s /usr/bin/ccache ~/bin/g++-4.8
- ln -s /usr/bin/ccache ~/bin/gcc-4.8
- ln -s /usr/bin/ccache ~/bin/gcc-4.8-size
- ln -s /usr/bin/ccache ~/bin/gcc-4.8-objcopy
- ln -s /usr/bin/ccache ~/bin/arm-none-eabi-g++
- ln -s /usr/bin/ccache ~/bin/arm-none-eabi-gcc
- ln -s /usr/bin/ccache ~/bin/arm-none-eabi-size
- ln -s /usr/bin/ccache ~/bin/arm-none-eabi-objcopy
- ln -s /usr/bin/ccache ~/bin/arm-linux-gnueabihf-g++
- ln -s /usr/bin/ccache ~/bin/arm-linux-gnueabihf-gcc
- ln -s /usr/bin/ccache ~/bin/arm-linux-gnueabihf-size
- ln -s /usr/bin/ccache ~/bin/arm-linux-gnueabihf-objcopy

script:
- pushd ArduCopter
- make px4-v2-solo -j8
- popd

before_deploy:
- mkdir $HOME/deploy_files
- cp ArduCopter/ArduCopter-v2.px4 $HOME/deploy_files
- cp modules/PX4Firmware/Build/px4fmu-v2_APM.build/firmware.elf $HOME/deploy_files/fmu.elf
- cp modules/PX4Firmware/Build/px4io-v2_default.build/firmware.elf $HOME/deploy_files/io.elf

deploy:
  provider: releases
  api_key: "$GITHUB_DEPLOY_API_KEY"
  file:
  - "$HOME/deploy_files/ArduCopter-v2.px4"
  - "$HOME/deploy_files/fmu.elf"
  - "$HOME/deploy_files/io.elf"
  on:
    tags: true
